In [21]:
cifar10_dataset_folder_path = 'C://Users/Admin/Downloads/cifar-10-batches-py'
import pickle

with open(cifar10_dataset_folder_path + '/data_batch_1', mode='rb') as file:
    batch = pickle.load(file, encoding='latin1')
    features = batch['data'].reshape((len(batch['data']), 3, 32, 32)).transpose(0, 2, 3, 1)
    #print(features.shape)
    labels = batch['labels']
    #features = batch['data'].reshape((len(batch['data']), 3, 32, 32))

features

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [12]:
features = batch['data']
print(features)
print(features.shape)

print(labels)
print(len(labels))

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 71  60  74 ...  68  69  68]
 [250 254 211 ... 215 255 254]
 [ 62  61  60 ... 130 130 131]]
(10000, 3072)
[6, 9, 9, 4, 1, 1, 2, 7, 8, 3, 4, 7, 7, 2, 9, 9, 9, 3, 2, 6, 4, 3, 6, 6, 2, 6, 3, 5, 4, 0, 0, 9, 1, 3, 4, 0, 3, 7, 3, 3, 5, 2, 2, 7, 1, 1, 1, 2, 2, 0, 9, 5, 7, 9, 2, 2, 5, 2, 4, 3, 1, 1, 8, 2, 1, 1, 4, 9, 7, 8, 5, 9, 6, 7, 3, 1, 9, 0, 3, 1, 3, 5, 4, 5, 7, 7, 4, 7, 9, 4, 2, 3, 8, 0, 1, 6, 1, 1, 4, 1, 8, 3, 9, 6, 6, 1, 8, 5, 2, 9, 9, 8, 1, 7, 7, 0, 0, 6, 9, 1, 2, 2, 9, 2, 6, 6, 1, 9, 5, 0, 4, 7, 6, 7, 1, 8, 1, 1, 2, 8, 1, 3, 3, 6, 2, 4, 9, 9, 5, 4, 3, 6, 7, 4, 6, 8, 5, 5, 4, 3, 1, 8, 4, 7, 6, 0, 9, 5, 1, 3, 8, 2, 7, 5, 3, 4, 1, 5, 7, 0, 4, 7, 5, 5, 1, 0, 9, 6, 9, 0, 8, 7, 8, 8, 2, 5, 2, 3, 5, 0, 6, 1, 9, 3, 6, 9, 1, 3, 9, 6, 6, 7, 1, 0, 9, 5, 8, 5, 2, 9, 0, 8, 8, 0, 6, 9, 1, 1, 6, 3, 7, 6, 6, 0, 6, 6, 1, 7, 1, 5, 8, 3, 6, 6, 8, 6, 8, 4, 6, 6, 1, 3, 8, 3, 4, 1, 7, 1, 3, 8, 5, 1, 1, 4, 0

In [6]:
batch

{'batch_label': 'training batch 1 of 5',
 'data': array([[ 59,  43,  50, ..., 140,  84,  72],
        [154, 126, 105, ..., 139, 142, 144],
        [255, 253, 253, ...,  83,  83,  84],
        ...,
        [ 71,  60,  74, ...,  68,  69,  68],
        [250, 254, 211, ..., 215, 255, 254],
        [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8),
 'filenames': ['leptodactylus_pentadactylus_s_000004.png',
  'camion_s_000148.png',
  'tipper_truck_s_001250.png',
  'american_elk_s_001521.png',
  'station_wagon_s_000293.png',
  'coupe_s_001735.png',
  'cassowary_s_001300.png',
  'cow_pony_s_001168.png',
  'sea_boat_s_001584.png',
  'tabby_s_001355.png',
  'muntjac_s_001000.png',
  'arabian_s_001354.png',
  'quarter_horse_s_000672.png',
  'passerine_s_000343.png',
  'camion_s_001895.png',
  'trailer_truck_s_000335.png',
  'dumper_s_000821.png',
  'alley_cat_s_000200.png',
  'accentor_s_000677.png',
  'frog_s_001671.png',
  'capreolus_capreolus_s_000051.png',
  'tomcat_s_000772.png',
  'pickere

In [7]:
batch.keys()

dict_keys(['batch_label', 'labels', 'data', 'filenames'])

In [13]:
myLabels = []
myLabels.append(3)

In [52]:
import PIL
from PIL import Image
import numpy as np
dim = 32
import os
labels = [0]
pic = np.zeros(shape=(1, 32, 32, 3))
folder1 = 'C://Users/Admin/Pictures/moon'
for filename in os.listdir(folder1):
    labels.append(0)
    pic1 = Image.open(folder1+'/'+filename)
    pic1 = pic1.resize((dim, dim), PIL.Image.ANTIALIAS)
    pic1 = np.array(pic1)
    pic1 = pic1.reshape(1, 32, 32, 3)
    pic = np.vstack([pic, pic1])
print('pic shape', pic.shape)
print(labels)
print('pic shape new', pic.shape)
newImage = Image.open('C://Users/Admin/Pictures/moon.png')
newImage1 = Image.open('C://Users/Admin/Pictures/moon1.jpg')

newImage = newImage.resize((dim, dim), PIL.Image.ANTIALIAS)
newImage1 = newImage1.resize((dim, dim), PIL.Image.ANTIALIAS)

newImageArr = np.array(newImage)
newImageArr1 = np.array(newImage1)

print('shape: ', newImageArr.shape)
print('shape1: ', newImageArr1.shape)

newImageArr = newImageArr.reshape(1, 32, 32, 3)
newImageArr1 = newImageArr1.reshape(1, 32, 32, 3)

print('new shape is: ', newImageArr.shape)
print('new shape1 is: ', newImageArr1.shape)


img1 = newImageArr
img2 = newImageArr1
img1 = np.vstack([img1, img2])
print('img1 shape is: ',img1.shape)
img1

pic shape (4, 32, 32, 3)
[0, 0, 0, 0]
pic shape new (4, 32, 32, 3)
shape:  (32, 32, 3)
shape1:  (32, 32, 3)
new shape is:  (1, 32, 32, 3)
new shape1 is:  (1, 32, 32, 3)
img1 shape is:  (2, 32, 32, 3)


array([[[[16, 16, 16],
         [17, 17, 17],
         [19, 19, 19],
         ...,
         [17, 17, 17],
         [17, 17, 17],
         [17, 17, 17]],

        [[13, 13, 13],
         [28, 28, 28],
         [61, 61, 61],
         ...,
         [17, 17, 17],
         [18, 18, 18],
         [18, 18, 18]],

        [[16, 16, 16],
         [16, 16, 16],
         [17, 17, 17],
         ...,
         [16, 16, 16],
         [26, 26, 26],
         [19, 19, 19]],

        ...,

        [[16, 16, 16],
         [17, 17, 17],
         [21, 21, 21],
         ...,
         [19, 19, 19],
         [17, 17, 17],
         [16, 16, 16]],

        [[16, 16, 16],
         [17, 17, 17],
         [22, 22, 22],
         ...,
         [23, 23, 23],
         [11, 11, 11],
         [39, 39, 39]],

        [[16, 16, 16],
         [17, 17, 17],
         [20, 20, 20],
         ...,
         [20, 20, 20],
         [15, 15, 15],
         [16, 16, 16]]],


       [[[ 5,  6, 11],
         [ 3,  4, 11],
         [ 2, 

In [33]:
import matplotlib.image as mpimg
folder1 = 'C://Users/Admin/Pictures/moon'
print(folder1)
def load_images(folder):
    images = []
    for filename in os.listdir(folder):
        print(folder+filename)
        img = mpimg.imread(os.path.join(folder, filename))
        if img is not None:
            images.append(img)
    return images

C://Users/Admin/Pictures/moon


In [34]:
import os
x = load_images(folder1)
x[0].shape

C://Users/Admin/Pictures/moonBlack-Moon-Wallpaper-19-1920x1080.jpg
C://Users/Admin/Pictures/moonmoon.png
C://Users/Admin/Pictures/moonmoon1.jpg


(1080, 1920, 3)

In [3]:
featuresaaa = batch['data'].reshape((len(batch['data']), 3, 32, 32))
featuresaaa.shape

NameError: name 'batch' is not defined

In [ ]:
features1 = batch['data'].reshape((len(batch['data']), 3, 32, 32)).transpose(0, 2, 3, 1)